name: Backend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/todo-three-tier-app
            git pull origin main

            cd backend
            source venv/bin/activate
            pip install -r requirements.txt

            pkill -f "python3 app.py" || true
            nohup python3 app.py > backend.log 2>&1 &
